README.md
=> Fix hasadna.org.il link

gtfs/retriever/gtfs_retrieve.py, gtfs/retriever/gtfs_utils.py
=> add gtfs download and archive script

postgres/postgis_queries.sql, siri/siri_parser.py
issue #42 
1. remove unnecessary fields
2. Change vehicle_location_lat and vehicle_location_lon to varchar(8) - make changes in code to round the result.
After pull request is accepted will run:
UPDATE siri_arrivals
SET vehicle_location_lat = NULL
AND vehicle_location_lon = NULL
WHERE vehicle_location_lat = '';
ALTER TABLE siri_arrivals
ALTER COLUMN vehicle_location_lat TYPE double precision USING round(vehicle_location_lat::numeric,5);
ALTER TABLE siri_arrivals
ALTER COLUMN vehicle_location_lon TYPE double precision USING round(vehicle_location_lonn::numeric,5);
=> Siri update script - reduce size

doc/working_with_GTFS.md, postgres/insert_gtfs.sql
Avoid HTTP 404 in documentation.
Fix table name in postgres DB creation.
=> Shai's first PR

README.md
just a link to the blog and github repository with the notebooks
=> added cjer Playing with GTFS link to README

gtfs/retriever/gtfs_retrieve.py
=> Download gtfs data cli tool

gtfs/retriever/Requirments.md
i founds that for executing the retriever i had to install 2 dependencies
=> Requirments.md

ROADMAP.md
You all are very much invited to comment and disscuss
=> Write a roadmap, resolves #65

gtfs/gtfs_utils/gtfs_utils/gtfs_stats.py
closes #115 
- start_stop_name, end_stop_name
- start_stop_desc, end_stop_desc
- route_mkt, route_direction, route_alternative (extracted from routes.txt route_desc)
=> add fields to trip_stats and route_stats

gtfs/gtfs_utils/setup.py
Fixing the travis build by locking some of the python packages we use
=> Fix travis python build

gtfs/gtfs_utils/gtfs_utils/gtfs_utils.py, notebooks/cluster_stats.ipynb
Same as #137 in a jupyter notebook
=> Add cluster stats notebook

gtfs/retriever/readme.md
=> Issue 176 documentation for gtfs utils

gtfs/gtfs_utils/setup.py
The build was broken because of a version conflict.
I've changed the version requirements so it won't break.
=> Fixed version conflict that was breaking the build

splunk/open-bus/local/data/ui/views/siri_investigator.xml, splunk/open-bus/local/props.conf, splunk/open-bus/metadata/local.meta
1. Change the way we extract the time to use TIME_PREFIX instead of TIMESTAMP_FIELDS.
1. Create a field alias from xD7timestamp to timestamp
=> fix timestamp extraction

pipeline/Daily_SIRI_Upload.pipeline, pipeline/GTFS_Download_And_Archive.pipeline, pipeline/SIRI_logs_ETL.pipeline, pipeline/check_for_new_SIRI_logs.pipeline, pipeline/readme.md
=> Jenkins pipeline jobs as code

gtfs/docs/source/route_stats.rst, gtfs/docs/source/trip_stats.rst, gtfs/gtfs_utils/gtfs_utils/config_example.json, gtfs/gtfs_utils/gtfs_utils/configuration.py, gtfs/gtfs_utils/gtfs_utils/core_calculations.py, gtfs/gtfs_utils/gtfs_utils/core_computations.py, gtfs/gtfs_utils/gtfs_utils/gtfs_stats.py, gtfs/gtfs_utils/gtfs_utils/local_files.py, gtfs/gtfs_utils/gtfs_utils/output.py, gtfs/gtfs_utils/gtfs_utils/partridge_helper.py, gtfs/gtfs_utils/gtfs_utils/s3.py
=>  Organize GTFS stats files

gtfs/gtfs_utils/gtfs_utils/core_computations.py
=> no more line_sep

gtfs/gtfs_utils/gtfs_utils/config.schema.json, gtfs/gtfs_utils/gtfs_utils/configuration.py, gtfs/gtfs_utils/tests/test_configuration.py
I had some free time so I rote the test,
and added a test for the example config
=> Configuration test

firebase/client/src/components/RideViewer/RideViewer.js
=> React key bug fix

gtfs/gtfs_utils/setup.py
Setup requirements should include only packages that required for running setup.py
https://stackoverflow.com/a/27271396/6136361 
We can try this to separate the installations requirements
=> rtd import error

pipeline/create_siri_csv_splunk.py
To save storage and increase efficiency - from now on duplicates are dropped from siri_logs when creating the csv for splunk. 
A field named num_duplicates is added instead which contains an int with the number of duplicates the record originally had.
=> Drop duplicates in create_siri_csv_splunk

data_stream/base_classes.py, data_stream/siri_log_parser.py, data_stream/test_siri_log_parser.py
=> add SQLite layer for siri paeser
